INSERT INTO SINGER (FIRST_NAME, LAST_NAME, BIRTH_DATE)
VALUES ('John', 'Mayer', '1977-10-16');
INSERT INTO SINGER (FIRST_NAME, LAST_NAME, BIRTH_DATE)
VALUES ('Eric', 'Clapton', '1945-03-30');
INSERT INTO SINGER (FIRST_NAME, LAST_NAME, BIRTH_DATE)
VALUES ('Jimi', 'Hendrix', '1942-11-27');

INSERT INTO ALBUM (SINGER_id, TITLE, RELEASE_DATE)
VALUES (1, 'The Search For Everything', '2017-01-20');
INSERT INTO ALBUM (SINGER_id, TITLE, RELEASE_DATE)
VALUES (1, 'Paradise Valley', '2013-08-19');
INSERT INTO ALBUM (SINGER_id, TITLE, RELEASE_DATE)
VALUES (1, 'Born and Raised', '2012-05-22');
INSERT INTO ALBUM (SINGER_id, TITLE, RELEASE_DATE)
VALUES (1, 'Battle Studies', '2009-11-17');
INSERT INTO ALBUM (SINGER_id, TITLE, RELEASE_DATE)
VALUES (2, 'From The Cradle ', '1994-09-13');
