#spring.datasource.schema=db/schema.sql
#spring.datasource.data=db/test-data.sql
#spring.datasource.initialize=true
spring:
  datasource:
    schema: db/schema.sql
    data: db/test-data.sql
    initialization-mode: never
    url: jdbc:mysql://localhost:3306/MUSICDB?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: se1124
