INSERT INTO SINGER (FIRST_NAME, LAST_NAME, BIRTH_DATE)
VALUES ('John', 'Mayer', '1977-10-16');
INSERT INTO SINGER (FIRST_NAME, LAST_NAME, BIRTH_DATE)
VALUES ('Eric', 'Clapton', '1945-03-30');
INSERT INTO SINGER (FIRST_NAME, LAST_NAME, BIRTH_DATE)
VALUES ('John', 'Butler', '1975-04-01');

INSERT INTO ALBUM (SINGER_id, TITLE, RELEASE_DATE)
VALUES (1, 'The Search For Everything', '2017-01-20');
INSERT INTO ALBUM (SINGER_id, TITLE, RELEASE_DATE)
VALUES (1, 'Battle Studies', '2009-11-17');
INSERT INTO ALBUM (SINGER_id, TITLE, RELEASE_DATE)
VALUES (2, ' From The Cradle ', '1994-09-13');

/* view the inserted data */
SELECT *
FROM SINGER;
SELECT *
FROM ALBUM;

/* simple join sample */
SELECT *
FROM ALBUM A,
     SINGER S
WHERE SINGER_ID = S.ID
  AND S.ID = 1;
